### ISSUE TITLE
Tap to shoot

### ISSUE THREAD

**Issue by sfoster** [sfoster/zed-gunner#5]
The cursor component gives us a "click" event when it intersects with an entity. Probably we want to tap/click on a control to actually shoot. 
Are there analogs to mouseenter/mouseleave events we can use to keep track of which entities are under the cursor?

**Comment by grogbeard** [comment]
In my first AR game on the shirts, I found tapping to be lackluster for a couple of reasons. Mostly this would be because you are holding your phone in a tight grip with one hand while furiously tapping at zombies with the other, which makes it harder to dislodge it. Secondly having your hand in a tapping position occludes part of the screen which is suboptimal because we wanna show the user our game, and let them see it. Lastly there is a very vain reason which is that tapping with a one-handed grip shakes your phone, and makes your internal microphone peak, so if you are recording your play experience it gets shakey and loud. 

I found this in the a-frame docs, did you see it? it mentions mouse enter's and junk. https://aframe.io/docs/0.9.0/components/cursor.html

**Comment by sfoster** [comment]
Sweet, I had found that page but didn't read far enough :)
Ok, gaze-based works for me. I'll have it so you have to hold the enemy in the cross-hairs for some fraction of a second before a shot is fired/damage is taken. So its not just a constant beam of bullets that sometimes happen to hit something.

**Comment by grogbeard** [comment]
OOh I like that! especially cause we could get a minigun spin-up sound so it on mouse over it would play the spin up then the firing noise after it for extra JUICE

**Comment by sfoster** [comment]
I think I have something like this implemented in 4e9e7bc023ca28828081a6d8bc402e51b5fbd2ec
